// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WalletApp.Persistence.Contexts;

#nullable disable

namespace WalletApp.Persistence.Migrations
{
    [DbContext(typeof(WalletAppDbContext))]
    [Migration("20230812100913_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WalletApp.Domain.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("AuthorizedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPending")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TransactionType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountId = 1,
                            Amount = 701.724059082979000m,
                            AuthorizedUser = "Author",
                            Date = new DateTime(2023, 7, 15, 16, 7, 40, 444, DateTimeKind.Unspecified).AddTicks(9311),
                            Description = "Some description",
                            IsPending = true,
                            Title = "Credit",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 2,
                            AccountId = 1,
                            Amount = 770.49225892973000m,
                            AuthorizedUser = "Author",
                            Date = new DateTime(2023, 7, 16, 11, 44, 59, 333, DateTimeKind.Unspecified).AddTicks(9770),
                            IsPending = false,
                            Title = "Credit",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 3,
                            AccountId = 2,
                            Amount = 475.838481912631000m,
                            AuthorizedUser = "Author",
                            Date = new DateTime(2023, 7, 16, 12, 10, 4, 378, DateTimeKind.Unspecified).AddTicks(5604),
                            IsPending = false,
                            Title = "Credit",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 4,
                            AccountId = 2,
                            Amount = 10.3361539263104000m,
                            AuthorizedUser = "Author",
                            Date = new DateTime(2023, 7, 17, 2, 54, 36, 354, DateTimeKind.Unspecified).AddTicks(540),
                            Description = "Some description",
                            IsPending = true,
                            Title = "Payment",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = 5,
                            AccountId = 2,
                            Amount = 739.854684070274000m,
                            Date = new DateTime(2023, 7, 17, 5, 21, 23, 419, DateTimeKind.Unspecified).AddTicks(8844),
                            IsPending = false,
                            Title = "Payment",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = 6,
                            AccountId = 2,
                            Amount = 739.21721131775000m,
                            AuthorizedUser = "Author",
                            Date = new DateTime(2023, 7, 18, 12, 51, 23, 386, DateTimeKind.Unspecified).AddTicks(2590),
                            IsPending = true,
                            Title = "Payment",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = 7,
                            AccountId = 1,
                            Amount = 769.254750156544000m,
                            AuthorizedUser = "Author",
                            Date = new DateTime(2023, 7, 18, 21, 50, 17, 592, DateTimeKind.Unspecified).AddTicks(6347),
                            Description = "Some description",
                            IsPending = true,
                            Title = "Credit",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 8,
                            AccountId = 2,
                            Amount = 719.027479379268000m,
                            Date = new DateTime(2023, 7, 21, 0, 27, 52, 352, DateTimeKind.Unspecified).AddTicks(8675),
                            Description = "Some description",
                            IsPending = false,
                            Title = "Credit",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 9,
                            AccountId = 1,
                            Amount = 926.680706265081000m,
                            AuthorizedUser = "Author",
                            Date = new DateTime(2023, 7, 22, 5, 31, 36, 705, DateTimeKind.Unspecified).AddTicks(7085),
                            Description = "Some description",
                            IsPending = false,
                            Title = "Payment",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = 10,
                            AccountId = 2,
                            Amount = 912.341801508485000m,
                            Date = new DateTime(2023, 7, 23, 5, 59, 13, 591, DateTimeKind.Unspecified).AddTicks(3145),
                            IsPending = false,
                            Title = "Credit",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 11,
                            AccountId = 2,
                            Amount = 86.1110153455057000m,
                            AuthorizedUser = "Author",
                            Date = new DateTime(2023, 7, 24, 6, 48, 38, 961, DateTimeKind.Unspecified).AddTicks(6897),
                            Description = "Some description",
                            IsPending = true,
                            Title = "Payment",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = 12,
                            AccountId = 1,
                            Amount = 289.483898339041000m,
                            AuthorizedUser = "Author",
                            Date = new DateTime(2023, 7, 25, 6, 59, 21, 870, DateTimeKind.Unspecified).AddTicks(3366),
                            IsPending = true,
                            Title = "Credit",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 13,
                            AccountId = 1,
                            Amount = 198.457637817378000m,
                            AuthorizedUser = "Author",
                            Date = new DateTime(2023, 7, 25, 14, 8, 2, 335, DateTimeKind.Unspecified).AddTicks(5405),
                            IsPending = false,
                            Title = "Payment",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = 14,
                            AccountId = 1,
                            Amount = 828.357225772103000m,
                            Date = new DateTime(2023, 7, 25, 14, 23, 18, 867, DateTimeKind.Unspecified).AddTicks(388),
                            IsPending = true,
                            Title = "Payment",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = 15,
                            AccountId = 2,
                            Amount = 795.235356744283000m,
                            Date = new DateTime(2023, 7, 25, 23, 13, 25, 484, DateTimeKind.Unspecified).AddTicks(444),
                            Description = "Some description",
                            IsPending = false,
                            Title = "Credit",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 16,
                            AccountId = 1,
                            Amount = 967.140426729544000m,
                            Date = new DateTime(2023, 7, 27, 5, 9, 40, 998, DateTimeKind.Unspecified).AddTicks(8919),
                            IsPending = true,
                            Title = "Payment",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = 17,
                            AccountId = 2,
                            Amount = 893.595142645919000m,
                            AuthorizedUser = "Author",
                            Date = new DateTime(2023, 7, 29, 8, 29, 5, 982, DateTimeKind.Unspecified).AddTicks(6807),
                            Description = "Some description",
                            IsPending = true,
                            Title = "Payment",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = 18,
                            AccountId = 2,
                            Amount = 865.451526170548000m,
                            Date = new DateTime(2023, 7, 30, 5, 0, 42, 244, DateTimeKind.Unspecified).AddTicks(4679),
                            Description = "Some description",
                            IsPending = true,
                            Title = "Payment",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = 19,
                            AccountId = 1,
                            Amount = 344.157441054058000m,
                            AuthorizedUser = "Author",
                            Date = new DateTime(2023, 8, 2, 16, 15, 54, 75, DateTimeKind.Unspecified).AddTicks(5310),
                            Description = "Some description",
                            IsPending = true,
                            Title = "Credit",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 20,
                            AccountId = 1,
                            Amount = 222.238754650841000m,
                            AuthorizedUser = "Author",
                            Date = new DateTime(2023, 8, 7, 2, 2, 34, 449, DateTimeKind.Unspecified).AddTicks(1004),
                            IsPending = false,
                            Title = "Payment",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = 21,
                            AccountId = 2,
                            Amount = 789.570397969155000m,
                            Date = new DateTime(2023, 8, 7, 4, 9, 12, 507, DateTimeKind.Unspecified).AddTicks(4498),
                            IsPending = false,
                            Title = "Credit",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 22,
                            AccountId = 1,
                            Amount = 36.3297257028562000m,
                            Date = new DateTime(2023, 8, 7, 7, 53, 37, 358, DateTimeKind.Unspecified).AddTicks(8252),
                            IsPending = false,
                            Title = "Payment",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = 23,
                            AccountId = 2,
                            Amount = 801.850138524724000m,
                            Date = new DateTime(2023, 8, 7, 15, 54, 39, 183, DateTimeKind.Unspecified).AddTicks(7940),
                            IsPending = true,
                            Title = "Credit",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 24,
                            AccountId = 2,
                            Amount = 28.2418998316961000m,
                            AuthorizedUser = "Author",
                            Date = new DateTime(2023, 8, 8, 22, 46, 3, 760, DateTimeKind.Unspecified).AddTicks(3045),
                            Description = "Some description",
                            IsPending = true,
                            Title = "Credit",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 25,
                            AccountId = 1,
                            Amount = 547.963378377792000m,
                            Date = new DateTime(2023, 8, 11, 0, 10, 23, 924, DateTimeKind.Unspecified).AddTicks(1574),
                            IsPending = false,
                            Title = "Credit",
                            TransactionType = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
