// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WalletApp.Persistence.Contexts;

#nullable disable

namespace WalletApp.Persistence.Migrations
{
    [DbContext(typeof(WalletAppDbContext))]
    [Migration("20230811011627_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WalletApp.Domain.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("AuthorizedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPending")
                        .HasColumnType("bit");

                    b.Property<decimal>("Sum")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TransactionType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountId = 1,
                            Date = new DateTime(2023, 7, 12, 8, 48, 34, 461, DateTimeKind.Unspecified).AddTicks(7047),
                            IsPending = false,
                            Sum = 606m,
                            Title = "TransactionType",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = 2,
                            AccountId = 1,
                            AuthorizedUser = "Author",
                            Date = new DateTime(2023, 7, 12, 20, 15, 31, 641, DateTimeKind.Unspecified).AddTicks(9430),
                            Description = "Some description",
                            IsPending = false,
                            Sum = 879m,
                            Title = "TransactionType",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = 3,
                            AccountId = 2,
                            Date = new DateTime(2023, 7, 16, 15, 22, 4, 150, DateTimeKind.Unspecified).AddTicks(236),
                            Description = "Some description",
                            IsPending = false,
                            Sum = 36m,
                            Title = "TransactionType",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 4,
                            AccountId = 2,
                            AuthorizedUser = "Author",
                            Date = new DateTime(2023, 7, 16, 20, 1, 12, 321, DateTimeKind.Unspecified).AddTicks(1662),
                            IsPending = false,
                            Sum = 995m,
                            Title = "TransactionType",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 5,
                            AccountId = 2,
                            AuthorizedUser = "Author",
                            Date = new DateTime(2023, 7, 18, 15, 42, 46, 118, DateTimeKind.Unspecified).AddTicks(2188),
                            Description = "Some description",
                            IsPending = true,
                            Sum = 610m,
                            Title = "TransactionType",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = 6,
                            AccountId = 1,
                            AuthorizedUser = "Author",
                            Date = new DateTime(2023, 7, 19, 9, 27, 27, 971, DateTimeKind.Unspecified).AddTicks(2604),
                            Description = "Some description",
                            IsPending = true,
                            Sum = 213m,
                            Title = "TransactionType",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 7,
                            AccountId = 1,
                            Date = new DateTime(2023, 7, 23, 9, 59, 22, 82, DateTimeKind.Unspecified).AddTicks(2593),
                            IsPending = false,
                            Sum = 198m,
                            Title = "TransactionType",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = 8,
                            AccountId = 2,
                            AuthorizedUser = "Author",
                            Date = new DateTime(2023, 7, 24, 3, 25, 43, 620, DateTimeKind.Unspecified).AddTicks(4868),
                            IsPending = true,
                            Sum = 311m,
                            Title = "TransactionType",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 9,
                            AccountId = 1,
                            Date = new DateTime(2023, 7, 27, 2, 20, 28, 711, DateTimeKind.Unspecified).AddTicks(8893),
                            IsPending = false,
                            Sum = 808m,
                            Title = "TransactionType",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = 10,
                            AccountId = 2,
                            Date = new DateTime(2023, 7, 29, 7, 1, 58, 692, DateTimeKind.Unspecified).AddTicks(526),
                            Description = "Some description",
                            IsPending = true,
                            Sum = 817m,
                            Title = "TransactionType",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = 11,
                            AccountId = 1,
                            Date = new DateTime(2023, 7, 29, 7, 39, 23, 713, DateTimeKind.Unspecified).AddTicks(6113),
                            Description = "Some description",
                            IsPending = true,
                            Sum = 283m,
                            Title = "TransactionType",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = 12,
                            AccountId = 2,
                            Date = new DateTime(2023, 7, 30, 9, 28, 8, 790, DateTimeKind.Unspecified).AddTicks(7637),
                            Description = "Some description",
                            IsPending = false,
                            Sum = 976m,
                            Title = "TransactionType",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 13,
                            AccountId = 1,
                            Date = new DateTime(2023, 7, 30, 10, 23, 2, 685, DateTimeKind.Unspecified).AddTicks(8692),
                            Description = "Some description",
                            IsPending = false,
                            Sum = 895m,
                            Title = "TransactionType",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = 14,
                            AccountId = 1,
                            AuthorizedUser = "Author",
                            Date = new DateTime(2023, 7, 30, 10, 34, 42, 270, DateTimeKind.Unspecified).AddTicks(6368),
                            Description = "Some description",
                            IsPending = true,
                            Sum = 458m,
                            Title = "TransactionType",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 15,
                            AccountId = 2,
                            Date = new DateTime(2023, 7, 30, 13, 12, 7, 589, DateTimeKind.Unspecified).AddTicks(7055),
                            IsPending = true,
                            Sum = 57m,
                            Title = "TransactionType",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = 16,
                            AccountId = 1,
                            AuthorizedUser = "Author",
                            Date = new DateTime(2023, 7, 30, 23, 42, 9, 301, DateTimeKind.Unspecified).AddTicks(3987),
                            IsPending = false,
                            Sum = 398m,
                            Title = "TransactionType",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = 17,
                            AccountId = 2,
                            AuthorizedUser = "Author",
                            Date = new DateTime(2023, 7, 31, 22, 44, 51, 4, DateTimeKind.Unspecified).AddTicks(5335),
                            IsPending = true,
                            Sum = 968m,
                            Title = "TransactionType",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = 18,
                            AccountId = 1,
                            Date = new DateTime(2023, 8, 1, 7, 25, 18, 697, DateTimeKind.Unspecified).AddTicks(1754),
                            IsPending = false,
                            Sum = 524m,
                            Title = "TransactionType",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 19,
                            AccountId = 2,
                            AuthorizedUser = "Author",
                            Date = new DateTime(2023, 8, 2, 8, 2, 12, 253, DateTimeKind.Unspecified).AddTicks(7261),
                            IsPending = false,
                            Sum = 150m,
                            Title = "TransactionType",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 20,
                            AccountId = 2,
                            Date = new DateTime(2023, 8, 3, 20, 11, 25, 113, DateTimeKind.Unspecified).AddTicks(875),
                            Description = "Some description",
                            IsPending = false,
                            Sum = 545m,
                            Title = "TransactionType",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 21,
                            AccountId = 2,
                            AuthorizedUser = "Author",
                            Date = new DateTime(2023, 8, 4, 13, 27, 54, 409, DateTimeKind.Unspecified).AddTicks(4689),
                            Description = "Some description",
                            IsPending = true,
                            Sum = 978m,
                            Title = "TransactionType",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 22,
                            AccountId = 2,
                            AuthorizedUser = "Author",
                            Date = new DateTime(2023, 8, 6, 20, 49, 33, 130, DateTimeKind.Unspecified).AddTicks(1677),
                            IsPending = true,
                            Sum = 181m,
                            Title = "TransactionType",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = 23,
                            AccountId = 1,
                            Date = new DateTime(2023, 8, 8, 5, 26, 11, 362, DateTimeKind.Unspecified).AddTicks(8880),
                            Description = "Some description",
                            IsPending = false,
                            Sum = 426m,
                            Title = "TransactionType",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 24,
                            AccountId = 2,
                            AuthorizedUser = "Author",
                            Date = new DateTime(2023, 8, 8, 22, 9, 18, 283, DateTimeKind.Unspecified).AddTicks(8209),
                            IsPending = true,
                            Sum = 727m,
                            Title = "TransactionType",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = 25,
                            AccountId = 2,
                            Date = new DateTime(2023, 8, 9, 17, 44, 19, 155, DateTimeKind.Unspecified).AddTicks(2646),
                            IsPending = true,
                            Sum = 669m,
                            Title = "TransactionType",
                            TransactionType = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
