// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WalletApp.Persistence.Contexts;

#nullable disable

namespace WalletApp.Persistence.Migrations
{
    [DbContext(typeof(WalletAppDbContext))]
    partial class WalletAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WalletApp.Domain.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<string>("AuthorizedUser")
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsPending")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TransactionType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountId = 1,
                            Amount = 562.35865511716941,
                            Date = new DateTime(2023, 7, 14, 2, 12, 20, 702, DateTimeKind.Utc).AddTicks(8244),
                            Description = "Some description",
                            IsPending = false,
                            Title = "Payment",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = 2,
                            AccountId = 2,
                            Amount = 751.04030737259302,
                            AuthorizedUser = "Author",
                            Date = new DateTime(2023, 7, 14, 6, 37, 50, 479, DateTimeKind.Utc).AddTicks(7303),
                            Description = "Some description",
                            IsPending = false,
                            Title = "Credit",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 3,
                            AccountId = 1,
                            Amount = 816.34156715047607,
                            Date = new DateTime(2023, 7, 17, 19, 22, 3, 569, DateTimeKind.Utc).AddTicks(7546),
                            IsPending = true,
                            Title = "Payment",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = 4,
                            AccountId = 2,
                            Amount = 373.45784739725116,
                            AuthorizedUser = "Author",
                            Date = new DateTime(2023, 7, 17, 23, 38, 43, 123, DateTimeKind.Utc).AddTicks(3109),
                            Description = "Some description",
                            IsPending = true,
                            Title = "Payment",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = 5,
                            AccountId = 2,
                            Amount = 128.29510480446126,
                            Date = new DateTime(2023, 7, 20, 3, 6, 52, 444, DateTimeKind.Utc).AddTicks(4331),
                            IsPending = true,
                            Title = "Payment",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = 6,
                            AccountId = 1,
                            Amount = 801.15362846393487,
                            Date = new DateTime(2023, 7, 21, 17, 15, 57, 707, DateTimeKind.Utc).AddTicks(8131),
                            IsPending = true,
                            Title = "Payment",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = 7,
                            AccountId = 1,
                            Amount = 748.40653567072707,
                            Date = new DateTime(2023, 7, 23, 4, 30, 16, 364, DateTimeKind.Utc).AddTicks(84),
                            IsPending = true,
                            Title = "Payment",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = 8,
                            AccountId = 1,
                            Amount = 677.09075097505365,
                            AuthorizedUser = "Author",
                            Date = new DateTime(2023, 7, 23, 8, 29, 52, 993, DateTimeKind.Utc).AddTicks(9124),
                            Description = "Some description",
                            IsPending = true,
                            Title = "Credit",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 9,
                            AccountId = 2,
                            Amount = 737.13427450123299,
                            AuthorizedUser = "Author",
                            Date = new DateTime(2023, 7, 24, 15, 36, 51, 371, DateTimeKind.Utc).AddTicks(4724),
                            Description = "Some description",
                            IsPending = true,
                            Title = "Payment",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = 10,
                            AccountId = 1,
                            Amount = 400.86128354186343,
                            Date = new DateTime(2023, 7, 25, 1, 9, 53, 73, DateTimeKind.Utc).AddTicks(562),
                            IsPending = false,
                            Title = "Payment",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = 11,
                            AccountId = 1,
                            Amount = 269.6238954904062,
                            Date = new DateTime(2023, 7, 26, 2, 59, 15, 535, DateTimeKind.Utc).AddTicks(9179),
                            Description = "Some description",
                            IsPending = false,
                            Title = "Credit",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 12,
                            AccountId = 1,
                            Amount = 70.643189356359713,
                            AuthorizedUser = "Author",
                            Date = new DateTime(2023, 7, 27, 0, 56, 57, 788, DateTimeKind.Utc).AddTicks(913),
                            IsPending = false,
                            Title = "Credit",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 13,
                            AccountId = 1,
                            Amount = 872.66651782325721,
                            AuthorizedUser = "Author",
                            Date = new DateTime(2023, 7, 27, 19, 23, 43, 669, DateTimeKind.Utc).AddTicks(8738),
                            Description = "Some description",
                            IsPending = true,
                            Title = "Payment",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = 14,
                            AccountId = 1,
                            Amount = 243.79243895584946,
                            Date = new DateTime(2023, 7, 28, 16, 18, 57, 628, DateTimeKind.Utc).AddTicks(7483),
                            IsPending = false,
                            Title = "Payment",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = 15,
                            AccountId = 1,
                            Amount = 181.49936471279858,
                            Date = new DateTime(2023, 7, 29, 10, 53, 29, 2, DateTimeKind.Utc).AddTicks(5098),
                            IsPending = false,
                            Title = "Credit",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 16,
                            AccountId = 2,
                            Amount = 266.6906715060735,
                            Date = new DateTime(2023, 7, 31, 8, 23, 8, 409, DateTimeKind.Utc).AddTicks(817),
                            Description = "Some description",
                            IsPending = true,
                            Title = "Payment",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = 17,
                            AccountId = 1,
                            Amount = 945.35667221486437,
                            AuthorizedUser = "Author",
                            Date = new DateTime(2023, 8, 1, 21, 14, 41, 530, DateTimeKind.Utc).AddTicks(1540),
                            Description = "Some description",
                            IsPending = true,
                            Title = "Credit",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 18,
                            AccountId = 1,
                            Amount = 198.22470493995715,
                            Date = new DateTime(2023, 8, 2, 4, 19, 10, 523, DateTimeKind.Utc).AddTicks(9882),
                            IsPending = true,
                            Title = "Credit",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 19,
                            AccountId = 2,
                            Amount = 243.17450290417364,
                            Date = new DateTime(2023, 8, 3, 6, 38, 38, 779, DateTimeKind.Utc).AddTicks(2575),
                            Description = "Some description",
                            IsPending = true,
                            Title = "Payment",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = 20,
                            AccountId = 1,
                            Amount = 651.0058867785342,
                            Date = new DateTime(2023, 8, 7, 7, 41, 50, 240, DateTimeKind.Utc).AddTicks(6240),
                            IsPending = false,
                            Title = "Payment",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = 21,
                            AccountId = 1,
                            Amount = 1.5396009295891577,
                            Date = new DateTime(2023, 8, 8, 8, 55, 30, 265, DateTimeKind.Utc).AddTicks(7789),
                            Description = "Some description",
                            IsPending = true,
                            Title = "Credit",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 22,
                            AccountId = 2,
                            Amount = 213.58240647180426,
                            Date = new DateTime(2023, 8, 9, 9, 54, 37, 141, DateTimeKind.Utc).AddTicks(2601),
                            IsPending = false,
                            Title = "Credit",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 23,
                            AccountId = 2,
                            Amount = 608.95819578494047,
                            AuthorizedUser = "Author",
                            Date = new DateTime(2023, 8, 11, 7, 37, 27, 874, DateTimeKind.Utc).AddTicks(6631),
                            Description = "Some description",
                            IsPending = true,
                            Title = "Payment",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = 24,
                            AccountId = 2,
                            Amount = 718.00568307686217,
                            Date = new DateTime(2023, 8, 11, 10, 59, 13, 991, DateTimeKind.Utc).AddTicks(4729),
                            Description = "Some description",
                            IsPending = false,
                            Title = "Payment",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = 25,
                            AccountId = 2,
                            Amount = 360.94761054793111,
                            AuthorizedUser = "Author",
                            Date = new DateTime(2023, 8, 11, 23, 37, 45, 142, DateTimeKind.Utc).AddTicks(77),
                            IsPending = true,
                            Title = "Credit",
                            TransactionType = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
