// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WalletApp.Persistence.Contexts;

#nullable disable

namespace WalletApp.Persistence.Migrations
{
    [DbContext(typeof(WalletAppDbContext))]
    partial class WalletAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WalletApp.Domain.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<string>("AuthorizedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPending")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TransactionType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountId = 2,
                            Amount = 431.55828949287343,
                            Date = new DateTime(2023, 7, 14, 19, 53, 32, 923, DateTimeKind.Unspecified).AddTicks(4519),
                            IsPending = false,
                            Title = "Credit",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 2,
                            AccountId = 2,
                            Amount = 752.89816641440848,
                            Date = new DateTime(2023, 7, 15, 0, 1, 30, 584, DateTimeKind.Unspecified).AddTicks(9551),
                            IsPending = false,
                            Title = "Payment",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = 3,
                            AccountId = 1,
                            Amount = 136.65546481626367,
                            Date = new DateTime(2023, 7, 16, 12, 23, 25, 855, DateTimeKind.Unspecified).AddTicks(2796),
                            Description = "Some description",
                            IsPending = false,
                            Title = "Credit",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 4,
                            AccountId = 1,
                            Amount = 614.78075003374215,
                            AuthorizedUser = "Author",
                            Date = new DateTime(2023, 7, 17, 9, 53, 36, 624, DateTimeKind.Unspecified).AddTicks(3160),
                            Description = "Some description",
                            IsPending = false,
                            Title = "Payment",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = 5,
                            AccountId = 1,
                            Amount = 286.5013193861725,
                            Date = new DateTime(2023, 7, 17, 14, 52, 52, 456, DateTimeKind.Unspecified).AddTicks(6969),
                            IsPending = true,
                            Title = "Payment",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = 6,
                            AccountId = 2,
                            Amount = 742.22944112910591,
                            AuthorizedUser = "Author",
                            Date = new DateTime(2023, 7, 17, 17, 48, 26, 252, DateTimeKind.Unspecified).AddTicks(6477),
                            Description = "Some description",
                            IsPending = true,
                            Title = "Payment",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = 7,
                            AccountId = 1,
                            Amount = 410.35440122955958,
                            Date = new DateTime(2023, 7, 17, 23, 57, 11, 885, DateTimeKind.Unspecified).AddTicks(4434),
                            Description = "Some description",
                            IsPending = true,
                            Title = "Payment",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = 8,
                            AccountId = 2,
                            Amount = 310.14144808382503,
                            AuthorizedUser = "Author",
                            Date = new DateTime(2023, 7, 19, 9, 46, 35, 919, DateTimeKind.Unspecified).AddTicks(5094),
                            Description = "Some description",
                            IsPending = true,
                            Title = "Credit",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 9,
                            AccountId = 2,
                            Amount = 169.92004286399754,
                            AuthorizedUser = "Author",
                            Date = new DateTime(2023, 7, 20, 10, 18, 13, 690, DateTimeKind.Unspecified).AddTicks(5536),
                            Description = "Some description",
                            IsPending = false,
                            Title = "Credit",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 10,
                            AccountId = 2,
                            Amount = 781.7909220134884,
                            AuthorizedUser = "Author",
                            Date = new DateTime(2023, 7, 21, 4, 22, 34, 744, DateTimeKind.Unspecified).AddTicks(3073),
                            Description = "Some description",
                            IsPending = false,
                            Title = "Credit",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 11,
                            AccountId = 1,
                            Amount = 117.0641462311427,
                            AuthorizedUser = "Author",
                            Date = new DateTime(2023, 7, 21, 6, 0, 36, 168, DateTimeKind.Unspecified).AddTicks(4474),
                            IsPending = true,
                            Title = "Payment",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = 12,
                            AccountId = 2,
                            Amount = 259.37918399401462,
                            AuthorizedUser = "Author",
                            Date = new DateTime(2023, 7, 21, 8, 3, 5, 777, DateTimeKind.Unspecified).AddTicks(2441),
                            IsPending = true,
                            Title = "Credit",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 13,
                            AccountId = 2,
                            Amount = 732.37177752013997,
                            AuthorizedUser = "Author",
                            Date = new DateTime(2023, 7, 23, 15, 36, 40, 683, DateTimeKind.Unspecified).AddTicks(9592),
                            IsPending = false,
                            Title = "Payment",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = 14,
                            AccountId = 2,
                            Amount = 145.90990570224128,
                            Date = new DateTime(2023, 7, 25, 15, 53, 30, 2, DateTimeKind.Unspecified).AddTicks(1020),
                            Description = "Some description",
                            IsPending = true,
                            Title = "Credit",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 15,
                            AccountId = 2,
                            Amount = 798.73456107013328,
                            Date = new DateTime(2023, 7, 26, 6, 37, 31, 643, DateTimeKind.Unspecified).AddTicks(2505),
                            IsPending = false,
                            Title = "Payment",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = 16,
                            AccountId = 2,
                            Amount = 457.52687722887708,
                            AuthorizedUser = "Author",
                            Date = new DateTime(2023, 7, 27, 0, 42, 15, 204, DateTimeKind.Unspecified).AddTicks(3344),
                            Description = "Some description",
                            IsPending = false,
                            Title = "Credit",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 17,
                            AccountId = 1,
                            Amount = 293.00126427052106,
                            AuthorizedUser = "Author",
                            Date = new DateTime(2023, 7, 29, 17, 15, 25, 804, DateTimeKind.Unspecified).AddTicks(4360),
                            Description = "Some description",
                            IsPending = true,
                            Title = "Credit",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 18,
                            AccountId = 1,
                            Amount = 834.41976149839206,
                            Date = new DateTime(2023, 7, 30, 6, 20, 36, 517, DateTimeKind.Unspecified).AddTicks(3236),
                            Description = "Some description",
                            IsPending = true,
                            Title = "Payment",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = 19,
                            AccountId = 2,
                            Amount = 480.8097543924107,
                            Date = new DateTime(2023, 7, 30, 7, 39, 14, 947, DateTimeKind.Unspecified).AddTicks(8521),
                            Description = "Some description",
                            IsPending = false,
                            Title = "Credit",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 20,
                            AccountId = 1,
                            Amount = 685.38987353245489,
                            Date = new DateTime(2023, 7, 31, 1, 24, 11, 934, DateTimeKind.Unspecified).AddTicks(9608),
                            IsPending = true,
                            Title = "Credit",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 21,
                            AccountId = 1,
                            Amount = 577.78645521163958,
                            AuthorizedUser = "Author",
                            Date = new DateTime(2023, 8, 1, 0, 40, 55, 556, DateTimeKind.Unspecified).AddTicks(2356),
                            IsPending = true,
                            Title = "Credit",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 22,
                            AccountId = 2,
                            Amount = 366.95248323106352,
                            AuthorizedUser = "Author",
                            Date = new DateTime(2023, 8, 2, 6, 45, 57, 939, DateTimeKind.Unspecified).AddTicks(2677),
                            Description = "Some description",
                            IsPending = false,
                            Title = "Credit",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 23,
                            AccountId = 1,
                            Amount = 447.22053162162047,
                            AuthorizedUser = "Author",
                            Date = new DateTime(2023, 8, 6, 0, 26, 43, 889, DateTimeKind.Unspecified).AddTicks(9766),
                            Description = "Some description",
                            IsPending = false,
                            Title = "Credit",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 24,
                            AccountId = 1,
                            Amount = 743.30673175927404,
                            AuthorizedUser = "Author",
                            Date = new DateTime(2023, 8, 7, 11, 33, 20, 303, DateTimeKind.Unspecified).AddTicks(8303),
                            Description = "Some description",
                            IsPending = false,
                            Title = "Payment",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = 25,
                            AccountId = 1,
                            Amount = 701.90706983360315,
                            Date = new DateTime(2023, 8, 12, 12, 9, 1, 27, DateTimeKind.Unspecified).AddTicks(5258),
                            IsPending = false,
                            Title = "Credit",
                            TransactionType = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
